on: [pull_request]
name: Check markdown links
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: List Commit Files
      id: list_commit_files
      run: |
        echo "Mardown Check will run on the following files:"
        cat ${HOME}/files.json
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        base-branch: 'main'
        config-file: 'mlc_config.json'
      
